WandB is initialized: True
[Checkpoint] Loaded checkpoints/ppo_checkpoint_ep50.pt (episode 50)
尝试连接 (1/5)...
尝试连接 (1/5)...
尝试连接 (1/5)...
尝试连接 (1/5)...
尝试连接 (1/5)...
连接成功！
连接成功！
连接成功！
连接成功！
连接成功！
尝试重置游戏地图
尝试重置游戏地图
尝试重置游戏地图
尝试重置游戏地图
尝试重置游戏地图
创建环境...
环境创建成功
创建环境...
环境创建成功
创建环境...
环境创建成功
创建环境...
环境创建成功
创建环境...
环境创建成功
Traceback (most recent call last):
  File "/app/env/safe_gym.py", line 129, in step
    observation, done, info = await self.env.step(actions)
  File "/app/env/gym.py", line 22, in step
    state = await self._send(self._state, actions, self._channel)
  File "/app/env/gym.py", line 64, in _send_next_state
    await self._client_fwd.send_next_state(channel, state, actions)
  File "/app/env/forward_model.py", line 79, in send_next_state
    await self.connection.send(json.dumps(packet))
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
Traceback (most recent call last):
  File "/app/env/safe_gym.py", line 129, in step
    observation, done, info = await self.env.step(actions)
  File "/app/env/gym.py", line 22, in step
    state = await self._send(self._state, actions, self._channel)
  File "/app/env/gym.py", line 64, in _send_next_state
    await self._client_fwd.send_next_state(channel, state, actions)
  File "/app/env/forward_model.py", line 79, in send_next_state
    await self.connection.send(json.dumps(packet))
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
Traceback (most recent call last):
  File "/app/env/safe_gym.py", line 129, in step
    observation, done, info = await self.env.step(actions)
  File "/app/env/gym.py", line 22, in step
    state = await self._send(self._state, actions, self._channel)
  File "/app/env/gym.py", line 64, in _send_next_state
    await self._client_fwd.send_next_state(channel, state, actions)
  File "/app/env/forward_model.py", line 79, in send_next_state
    await self.connection.send(json.dumps(packet))
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
Traceback (most recent call last):
  File "/app/env/safe_gym.py", line 129, in step
    observation, done, info = await self.env.step(actions)
  File "/app/env/gym.py", line 22, in step
    state = await self._send(self._state, actions, self._channel)
  File "/app/env/gym.py", line 64, in _send_next_state
    await self._client_fwd.send_next_state(channel, state, actions)
  File "/app/env/forward_model.py", line 79, in send_next_state
    await self.connection.send(json.dumps(packet))
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
Traceback (most recent call last):
  File "/app/env/safe_gym.py", line 129, in step
    observation, done, info = await self.env.step(actions)
  File "/app/env/gym.py", line 22, in step
    state = await self._send(self._state, actions, self._channel)
  File "/app/env/gym.py", line 64, in _send_next_state
    await self._client_fwd.send_next_state(channel, state, actions)
  File "/app/env/forward_model.py", line 79, in send_next_state
    await self.connection.send(json.dumps(packet))
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
开始 Episode 51/10000
开始 Episode 51/10000
Step 错误: Object of type ndarray is not JSON serializable
Step 错误: Object of type ndarray is not JSON serializable
Step 错误: Object of type ndarray is not JSON serializable
Step 错误: Object of type ndarray is not JSON serializable
Step 错误: Object of type ndarray is not JSON serializable
Traceback (most recent call last):
  File "train_multi_env.py", line 213, in <module>
    asyncio.run(run_training())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "train_multi_env.py", line 128, in run_training
    prev_state = gym_manager.current_states[env_idx]["_prev_state"]
TypeError: 'NoneType' object is not subscriptable