[Checkpoint] 没找到已有模型，从头训练
开始训练，共 10000 轮!!!!!!!!!!
开始 Episode 1/10000
尝试连接 (1/5)...
连接成功！
尝试重置游戏地图
创建环境...
环境创建成功
Step 1, Reward: -1.05, Total: -1.05
Step 11, Reward: -0.54, Total: -2.59
Step 21, Reward: 0.44, Total: -8.16
Step 31, Reward: 0.00, Total: -6.41
Step 41, Reward: 0.14, Total: -4.86
Step 51, Reward: 0.14, Total: -6.24
Step 61, Reward: -0.24, Total: -6.20
警告: 有一个队伍没有活着的单位，跳出当前 episode
/app/agent/ppo_agent.py:255: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:261.)
  states = torch.tensor(states, dtype=torch.float32).to(self.device)
Traceback (most recent call last):
  File "train.py", line 304, in <module>
    asyncio.run(run_training())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "train.py", line 210, in run_training
    "benchmark/num_episode_buffer": num_episode_buffer,
UnboundLocalError: local variable 'num_episode_buffer' referenced before assignment
Update stats - Policy loss: 0.0460, Value loss: 25.6215, Total loss: 25.6676
关闭环境连接...
Connection with server closed
Connection with server closed
环境连接已关闭